name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - master

jobs:
  hexo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: nxvxl/gh-actions-hexo-deploy-gh-pages
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
